version: '3'

networks:
    bibbox-default-network:
    #   external: true

services:
  bibbox-molgenis-frontend:
    image: molgenis/molgenis-frontend:8.7.2
    container_name: bibbox-molgenis-frontend
    ports:
      - "80:80"
    networks:
      - bibbox-default-network
    volumes: 
      - ./data/backend.conf:/etc/nginx/proxy.d/backend.conf
    depends_on:
      - bibbox-molgenis
    links:
      - bibbox-molgenis:molgenis
    # proxy:
    #  TYPE: PRIMARY
    #  URLPREFIX: bibbox
    #  TEMPLATE: default
    #  DISPLAYNAME: 'Molgenis'  

  bibbox-molgenis:
    image: crs4/molgenis-app:ejprd-dev-v20
    container_name: bibbox-molgenis
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - molgenis.home=/home/molgenis
      - opencpu.uri.host=opencpu
      - elasticsearch.transport.addresses=elasticsearch:9300
      - db_uri=jdbc:postgresql://postgres/molgenis
      - db_user=molgenis
      - db_password=molgenis
      - admin.password=admin
      - MINIO_BUCKET_NAME=molgenis
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=molgenis
      - MINIO_SECRET_KEY=molgenis
      - MOLGENIS_MAX_FILE_MB=150
      - "CATALINA_OPTS=-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
    ports:
        - "8080:8080"
    links:
        - bibbox-molgenis-postgres:postgres
        - bibbox-molgenis-minio:minio
        - bibbox-molgenis-elasticsearch:elasticsearch
        - bibbox-molgenis-opencpu:opencpu
    volumes:
      - ./data/home/molgenis:/home/molgenis
    depends_on:
      - bibbox-molgenis-postgres

  bibbox-molgenis-postgres:
    image: postgres:11-alpine
    container_name: bibbox-molgenis-postgres
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    networks:
      - bibbox-default-network
    ports:
      - "5432:5432"
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
  bibbox-molgenis-elasticsearch:
    image: molgenis/molgenis-elasticsearch:1.0.0
    container_name: bibbox-molgenis-elasticsearch
    environment:
      - cluster.name=molgenis
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - bibbox-default-network
    ports:
      - "9200:9200"
      - "9300:9300"
  bibbox-molgenis-kibana:
    image: docker.elastic.co/kibana/kibana:5.5.3
    container_name: bibbox-molgenis-kibana
    profiles:
      - audit
    networks:
      - bibbox-default-network
    ports:
      - "5601:5601"
  bibbox-molgenis-kibana-dashboard:
    user: 0:0
    image: docker.elastic.co/kibana/kibana:5.5.3
    container_name: bibbox-molgenis-kibana-dashboard
    profiles:
      - audit
    command:
      - "/bin/sh"
      - "-c"
      - "/root/dashboard/import.sh"
    environment:
      DASHBOARD_FILE: https://raw.githubusercontent.com/molgenis/molgenis/master/.kibana/dashboard.json
    networks:
      - bibbox-default-network
    volumes:
      - ./data:/root/dashboard:ro
  bibbox-molgenis-filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.9.3
    container_name: bibbox-molgenis-filebeat
    profiles:
      - audit
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - bibbox-default-network
    volumes:
      - ./data/usr/share/filebeat/input/:/usr/share/filebeat/input/
      - ./data/usr/share/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - bibbox-molgenis-elasticsearch
  bibbox-molgenis-opencpu:
    image: molgenis/opencpu:opencpu-release-2019-03-20_12-07-11
    container_name: bibbox-molgenis-opencpu
#    profiles:
#      - opencpu
    networks:
      - bibbox-default-network
    ports:
      - "8004:8004"
  bibbox-molgenis-minio:
    image: minio/minio:RELEASE.2019-03-20T22-38-47Z
    container_name: bibbox-molgenis-minio
    volumes:
      - ./data/minio/data:/data
    networks:
      - bibbox-default-network
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
    command: server /data

